language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: red-applicant-tracker
  api_key:
    secure: Qmy7NneVYD6W/9BqJ89NWMV3Zkr4np9Gsj42j+U8N2hlRGJs33Ze95h1lgmRqdLPxjWWE7yiMgzNN1GaN2MjqNZPVV/sJEnbt5g1tdVe6XKjQbCwoH2HMuqDfHpm9RTm6xoDgAnx98we3ff6ihaXE6bnrykaUsj+Q5xRem1MUqz+aoVDypk2Ek8EdrcXNvOd5gbqvDl3MhTzf0jRR1GjTlDjCdJqsN7yoOyrD0/aL8qdBoCPkZ4f+YOm2iO/zNWuHfdfV9FhInB/2XrgZZ8eaTJnlYnZNhTVHbsLDrv0BtVza7SnPMz7v8Sw8q2/zTayawT4woSiQYX7FjbP8W2tSqXfNetQ1wzgfCsDPFwZrZaOYJAVMXEHz4AYhpoAf5ikSprT3c5jnOin+dhJRP1Llfdrwbfirw1UxAuc8KDEexrCsw6npN/mQwvCNCB9Dx7ZGq5AesisqgfwTCVD9qznv62IXJiPyxaMOGg/nnvn0YqEE2VPTv5obKedsPhtaI2v2rfktYT4wi0A/CJF39WB4CGCR+1HpoUCQE96+lElNbo6XgZK/113DgYUNcb9HPxwCwVCzzGiQ5EiG4f8Q05rZtED2BJzL2oBQZkaYrcXHaDx9SMJXPs1RDW0vEjdrGIdNSvxBHf2+WVhhzcuRaYgxewMIYs5802BCGFghMHB7Ug=
